name: CI
on: 
    push:
        branches:
            - master
        paths-ignore:
            - '**.md'
    pull_request:
        paths-ignore:
            - '**.md'
jobs:
    tests:
        name: Tests
        runs-on: macOS-latest
        steps:
            - uses: actions/checkout@v2

            - name: Decrypt Google Services
              run: ./decrypt-google-services.sh
              env:
                GOOGLE_SERVICES_SECRET: ${{secrets.GOOGLE_SERVICES_SECRET}}

            - name: Set up JDK 1.8
              uses: actions/setup-java@v1
              with:
                java-version: 1.8

            # Validate the Gradle wrapper JAR files.
            - name: Validate Gradle Wrapper
              uses: gradle/wrapper-validation-action@v1

            # Clean gradle cache to stay within github's cache size limits
            - name: Clean Gradle Cache
              run: rm -rf ~/.gradle/caches

            # Restore the cache
            - uses: actions/cache@v1
              with:
                  path: ~/.gradle/caches
                  key: gradle-${{ runner.os }}-${{ hashFiles('**/build.gradle') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}

            - name: Spotless
              run: ./gradlew spotlessApply

            - name: Unit Tests
              run: ./gradlew testDebugUnitTest

            - name: Instrumentation Tests
              uses: reactivecircus/android-emulator-runner@v2
              with:
                  api-level: 29
                  arch: x86_64
                  script: ./gradlew connectedDebugAndroidTest