name: CI
on: [push]
    # push:
    #     branches:
    #         - master
    #     paths-ignore:
    #         - '*.md'
    # pull_request:
    #     branches:
    #         - master
    #     paths-ignore:
    #         - '*.md'
jobs:
    tests:
        name: Tests
        runs-on: macOS-latest
        steps:
            - uses: actions/checkout@v2

            - name: Set up JDK 1.8
              uses: actions/setup-java@v1
              with:
                java-version: 1.8

            # Validate the Gradle wrapper JAR files.
            - name: Validate Gradle Wrapper
              uses: gradle/wrapper-validation-action@v1

            # Clean gradle cache to stay within github's cache size limits
            - name: Clean Gradle Cache
              run: rm -rf ~/.gradle/caches

            # Restore the cache
            - uses: actions/cache@v1
              with:
                  path: ~/.gradle/caches
                  key: gradle-${{ runner.os }}-${{ hashFiles('**/build.gradle') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}

            - name: Add Google Services
              run: echo -n $GOOGLE_SERVICES | base64 --decode > app/google-services.json

            - name: Spotless
              run: ./gradlew spotlessApply

            - name: Lint
              run: ./gradlew lintDebug

            - name: Unit Tests
              run: ./gradlew testDebugUnitTest

            - name: Instrumentation Tests
              uses: reactivecircus/android-emulator-runner@v2
              with:
                  api-level: 29
                  arch: x86_64
                  script: ./gradlew connectedDebugAndroidTest