name: CI
on: 
    push:
        branches:
            - master
        paths-ignore:
            - '**.md'
    pull_request:
        paths-ignore:
            - '**.md'
jobs:
    tests:
        name: Tests
        runs-on: macOS-latest
        steps:
            - uses: actions/checkout@v2
                
            - uses: actions/setup-java@v2
              with:
                distribution: 'adopt'
                java-version: '11'
                check-latest: true

            # Validate the Gradle wrapper JAR files.
            - name: Validate Gradle Wrapper
              uses: gradle/wrapper-validation-action@v1

            # Clean gradle cache to stay within github's cache size limits
            - name: Clean Gradle Cache
              run: rm -rf ~/.gradle/caches

            # Restore the cache
            - uses: actions/cache@v1
              with:
                  path: ~/.gradle/caches
                  key: gradle-${{ runner.os }}-${{ hashFiles('**/build.gradle') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}

            - name: Spotless
              run: ./gradlew spotlessCheck

            - name: Unit Tests
              run: ./gradlew testDevDebugUnitTest

            - name: Instrumentation Tests
              uses: reactivecircus/android-emulator-runner@v2
              with:
                  api-level: 29
                  arch: x86_64
                  script: ./gradlew connectedDevDebugAndroidTest
